baseURL = "https://davoodya.ir/articles/"
languageCode = "fa"
title = "مقالات داوود یحیی – Davood Yahya Articles"
defaultContentLanguage = "fa"
theme = 'ananke'
enableRobotsTXT = true
relativeURLs = false
canonifyURLs = true

# Summary settings
summaryLength = 70
hasCJKLanguage = true

# Pagination
[pagination]
pagerSize = 10

# Output formats for search
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
