baseURL = "https://davoodya.ir/"
languageCode = "fa"
title = "مقالات داوود یاحی – Davood Yahay Articles"
defaultContentLanguage = "fa"
theme = 'ananke'
enableRobotsTXT = true
relativeURLs = false
canonifyURLs = false

# Summary settings
summaryLength = 70
hasCJKLanguage = true

# Pagination
[pagination]
pagerSize = 4

# Output formats for search
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
taxonomy = ["HTML", "RSS", "JSON"]
term = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

